// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Outscale
{
    [OutscaleResourceType("outscale:index:Yandom")]
    public partial class Yandom : global::Pulumi.CustomResource
    {
        [Output("length")]
        public Output<int> Length { get; private set; } = null!;

        [Output("result")]
        public Output<string> Result { get; private set; } = null!;


        /// <summary>
        /// Create a Yandom resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Yandom(string name, YandomArgs args, CustomResourceOptions? options = null)
            : base("outscale:index:Yandom", name, args ?? new YandomArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Yandom(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("outscale:index:Yandom", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Yandom resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Yandom Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Yandom(name, id, options);
        }
    }

    public sealed class YandomArgs : global::Pulumi.ResourceArgs
    {
        [Input("length", required: true)]
        public Input<int> Length { get; set; } = null!;

        public YandomArgs()
        {
        }
        public static new YandomArgs Empty => new YandomArgs();
    }
}
