# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *
from .yandom import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "outscale",
  "mod": "index",
  "fqn": "pulumi_outscale",
  "classes": {
   "outscale:index:Random": "Random",
   "outscale:index:Yandom": "Yandom"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "outscale",
  "token": "pulumi:providers:outscale",
  "fqn": "pulumi_outscale",
  "class": "Provider"
 }
]
"""
)
